### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Hiruro** [martinkorelic/joplin-plugin-spoilers#3]
This is what I get when I do ctrl+alt+p and ctrl+alt+o

![image](https://user-images.githubusercontent.com/89399305/130460400-15668d54-eea8-454e-99a0-398974474ac6.png)

Did I miss something or is it a bug?

Thanks

**Comment by VincentLawRei** [comment]
Same.
Joplin version = 2.3.5.

**Comment by martinkorelic** [comment]
@Hiruro @VincentLawRei 
Unfortunately if you are using the rich markdown editor instead of the side-by-side editor, the plugin will not work.
Rich markdown does not offer support to other plugins, to my knowledge.

[More information about the Rich markdown editor limitations](https://joplinapp.org/rich_text_editor/).
