### ISSUE TITLE
Cannot print out spoiler block

### ISSUE THREAD

**Issue by ghost** [martinkorelic/joplin-plugin-spoilers#4]
Win10Pro | Joplin V2.4.12

I've test it with a blank `userstyle.css` and just put in:

```
@media print {

  /* Hides the side arrow */
  .summary-title:before {
    content: "";
  }

  #spoiler-block-body {
      /* Shows the body contents */
      display: block;
      animation: none;
  }
}
```

But when I print it out, it just print out the `]:` and `:[` with plain text content.

**Comment by martinkorelic** [comment]
Can't seem to recreate the problem, for me it prints out normally.
Does the spoiler block appear normal in the text editor preview?

**Comment by Nacandev** [comment]
I can use spoiler without problem when taking notes, the only problem is cannot print out. And I'm not the only one met this problem [Joplin Forum](https://discourse.joplinapp.org/t/css-theme-ohmine-dark-theme/21000/21?u=nacandev). 

I'm not so sure why cannot print out , but, did you test it on a clean Joplin?

And due to upgrade my laptop to Windows 11 Pro, I've format my drive and reinstalled everything. So, my latest tested is on Win11Pro and Joplin V2.5.10, but the problem is still the same.

**Comment by ghost** [comment]
Ok, I finally found that it is only works when I try to `export` a PDF but it doesn't work when go to `File` > `Print` to create a PDF. Is there any solution for this?
